apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Samir-CloudAwswithDevops/kubernetes-ingress-deployment.git
    targetRevision: main
    path: k8s-files
    directory:
      include: ingress.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
